// Generated by commsdsl2tools_qt v6.3.0

#pragma once

#include "cc_mqtt311/Message.h"
#include "cc_tools_qt/MessageBase.h"
#include "cc_tools_qt_plugin/cc_mqtt311/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt311
{

class Message : public
    cc_tools_qt::MessageBase<
        ::cc_mqtt311::Message
    >
{
protected:
    virtual const QVariantList& extraTransportFieldsPropertiesImpl() const override;
};

} // namespace cc_mqtt311

} // namespace cc_tools_qt_plugin
