// Generated by commsdsl2tools_qt v7.1.0

/// @file
/// @brief Contains definition of the default options for plugin.

#pragma once

#include "cc_mqtt311/options/AllMessagesDynMemMsgFactoryDefaultOptions.h"
#include "cc_mqtt311/options/DefaultOptions.h"
#include "cc_tools_qt_plugin/cc_mqtt311/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt311
{

namespace options
{

using DefaultOptions =
    ::cc_mqtt311::options::AllMessagesDynMemMsgFactoryDefaultOptionsT<
        ::cc_mqtt311::options::DefaultOptions
    >;

} // namespace options

} // namespace cc_mqtt311

} // namespace cc_tools_qt_plugin
