// Generated by commsdsl2tools_qt v6.3.2

/// @file
/// @brief Contains definition of the options for framing which force usage of message factory.

#pragma once

#include "cc_tools_qt_plugin/cc_mqtt311/factory/AllMessagesDynMemMsgFactory.h"
#include "cc_tools_qt_plugin/cc_mqtt311/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt311
{

namespace options
{

struct MsgFactoryFrameOptions : public cc_tools_qt_plugin::cc_mqtt311::options::DefaultOptions
{
    template <typename TInterface, typename TAllMessages, typename... TOptions>
    using MsgFactory = cc_tools_qt_plugin::cc_mqtt311::factory::AllMessagesDynMemMsgFactory;
};

} // namespace options

} // namespace cc_mqtt311

} // namespace cc_tools_qt_plugin
