// Generated by commsdsl2tools_qt v6.3.3

#pragma once

#include <QtCore/QVariantList>
#include "cc_mqtt311/message/Pubrec.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt_plugin/cc_mqtt311/Message.h"
#include "cc_tools_qt_plugin/cc_mqtt311/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt311
{

namespace message
{

class Pubrec : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqtt311::message::Pubrec<cc_tools_qt_plugin::cc_mqtt311::Message, cc_tools_qt_plugin::cc_mqtt311::options::DefaultOptions>,
        Pubrec
    >
{
public:
    Pubrec();
    Pubrec(const Pubrec&) = delete;
    Pubrec(Pubrec&&) = delete;
    virtual ~Pubrec();
    Pubrec& operator=(const Pubrec&);
    Pubrec& operator=(Pubrec&&);

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
};

} // namespace message

} // namespace cc_mqtt311

} // namespace cc_tools_qt_plugin
