// Generated by commsdsl2tools_qt v6.3.0

#pragma once

#include <tuple>
#include <QtCore/QVariantList>
#include "cc_tools_qt/TransportMessageBase.h"
#include "cc_tools_qt_plugin/cc_mqtt311/options/DefaultOptions.h"
#include "cc_mqtt311/frame/Frame.h"
#include "cc_tools_qt_plugin/cc_mqtt311/Message.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt311
{

namespace frame
{

struct FrameTransportMessageFields
{
    using All =
        std::tuple<
            ::cc_mqtt311::frame::FrameLayers<cc_tools_qt_plugin::cc_mqtt311::options::DefaultOptions>::IdAndFlagsMembers::IdAndFlagsField,
            ::cc_mqtt311::frame::FrameLayers<cc_tools_qt_plugin::cc_mqtt311::options::DefaultOptions>::SizeMembers::Size,
            ::cc_mqtt311::frame::FrameLayers<cc_tools_qt_plugin::cc_mqtt311::options::DefaultOptions>::Data::Field
        >;
    static const QVariantList& props();
};

class FrameTransportMessage : public
    cc_tools_qt::TransportMessageBase<
        cc_tools_qt_plugin::cc_mqtt311::Message,
        FrameTransportMessageFields::All
    >
{
protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
};

} // namespace frame

} // namespace cc_mqtt311

} // namespace cc_tools_qt_plugin
