// Generated by commsdsl2tools_qt v7.1.0

#include "Plugin_CC_MQTT_v3_1_1.h"

#include "Protocol_CC_MQTT_v3_1_1.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt311
{

namespace plugin
{

Plugin_CC_MQTT_v3_1_1::Plugin_CC_MQTT_v3_1_1() :
    Base(Type_Protocol)
{
}

Plugin_CC_MQTT_v3_1_1::~Plugin_CC_MQTT_v3_1_1() = default;

cc_tools_qt::ToolsProtocolPtr Plugin_CC_MQTT_v3_1_1::createProtocolImpl()
{
    return cc_tools_qt::ToolsProtocolPtr(new Protocol_CC_MQTT_v3_1_1());
}

} // namespace plugin

} // namespace cc_mqtt311

} // namespace cc_tools_qt_plugin
