// Generated by commsdsl2tools_qt v6.3.2

#include "Plugin_CC_MQTT_v3_1_1.h"

#include "Protocol_CC_MQTT_v3_1_1.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqtt311
{

namespace plugin
{

Plugin_CC_MQTT_v3_1_1::Plugin_CC_MQTT_v3_1_1() :
    m_protocol(new Protocol_CC_MQTT_v3_1_1())
{
    pluginProperties()
        .setProtocolCreateFunc(
            [this]() noexcept -> cc_tools_qt::ProtocolPtr
            {
                return m_protocol;
            })
    ;
}

Plugin_CC_MQTT_v3_1_1::~Plugin_CC_MQTT_v3_1_1() = default;

} // namespace plugin

} // namespace cc_mqtt311

} // namespace cc_tools_qt_plugin
